// GENERATED by packages/db/scripts/gen-types.mjs from the v2 database (api schema). Do not edit by hand.
// Regenerate: scripts/v2-db-test.sh with V2_DB_WRITE_TYPES=1 (or pnpm --filter @netprophet/db gen-types against a migrated DB).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  api: {
    Tables: { [_ in never]: never };
    Views: {
      areas: {
        Row: {
          id: string | null;
          region: string | null;
          name_el: string | null;
          name_en: string | null;
          sort: number | null;
        };
        Relationships: [];
      };
      badge_defs: {
        Row: {
          key: string | null;
          name_el: string | null;
          name_en: string | null;
          counter: string | null;
          thresholds: number[] | null;
          tier3_reward: Json | null;
          sort: number | null;
        };
        Relationships: [];
      };
      cosmetic_items: {
        Row: {
          id: string | null;
          category: string | null;
          key: string | null;
          name_el: string | null;
          name_en: string | null;
          kind: string | null;
          price_eur: number | null;
          earn_rule_text: string | null;
          assets: Json | null;
          sport_id: string | null;
        };
        Relationships: [];
      };
      leaderboard_monthly: {
        Row: {
          month_key: string | null;
          user_id: string | null;
          display_name: string | null;
          points: number | null;
          rank: number | null;
        };
        Relationships: [];
      };
      match_results: {
        Row: {
          match_id: string | null;
          winner_side: number | null;
          sets: Json | null;
          score_summary: string | null;
          retired: boolean | null;
          walkover: boolean | null;
          entered_at: string | null;
        };
        Relationships: [];
      };
      match_splits: {
        Row: {
          match_id: string | null;
          total: number | null;
          side1: number | null;
          side2: number | null;
        };
        Relationships: [];
      };
      matches: {
        Row: {
          id: string | null;
          sport_id: string | null;
          format: string | null;
          status: string | null;
          starts_at: string | null;
          venue: string | null;
          area_id: string | null;
          tournament_id: string | null;
          round: string | null;
          source: string | null;
          counts_for_levels: boolean | null;
          created_at: string | null;
          sides: Json | null;
        };
        Relationships: [];
      };
      my_badges: {
        Row: {
          badge_key: string | null;
          counter: number | null;
          tier: number | null;
          tier_up_at: string | null;
        };
        Relationships: [];
      };
      my_cosmetics: {
        Row: {
          item_id: string | null;
          source: string | null;
          at: string | null;
        };
        Relationships: [];
      };
      my_entitlements: {
        Row: {
          id: string | null;
          key: string | null;
          source: string | null;
          status: string | null;
          starts_at: string | null;
          ends_at: string | null;
        };
        Relationships: [];
      };
      my_equipped: {
        Row: {
          category: string | null;
          item_id: string | null;
        };
        Relationships: [];
      };
      my_follows: {
        Row: {
          player_id: string | null;
          relation: string | null;
          source: string | null;
          created_at: string | null;
        };
        Relationships: [];
      };
      my_freezes: {
        Row: {
          id: string | null;
          kind: string | null;
          source: string | null;
          acquired_at: string | null;
          used_at: string | null;
        };
        Relationships: [];
      };
      my_game_state: {
        Row: {
          user_id: string | null;
          total_points: number | null;
          streak: number | null;
          streak_best: number | null;
          chain: number | null;
          votes_cast: number | null;
          votes_correct: number | null;
          votes_since_free_freeze: number | null;
          active_days: number | null;
          last_active_day: string | null;
        };
        Relationships: [];
      };
      my_inbox: {
        Row: {
          id: string | null;
          kind: string | null;
          ref: string | null;
          payload: Json | null;
          created_at: string | null;
          seen_at: string | null;
        };
        Relationships: [];
      };
      my_notifications: {
        Row: {
          id: string | null;
          type: string | null;
          payload: Json | null;
          channel: string | null;
          scheduled_at: string | null;
          sent_at: string | null;
          read_at: string | null;
          created_at: string | null;
        };
        Relationships: [];
      };
      my_points_ledger: {
        Row: {
          id: number | null;
          delta: number | null;
          reason: string | null;
          ref_type: string | null;
          ref_id: string | null;
          month_key: string | null;
          created_at: string | null;
        };
        Relationships: [];
      };
      my_profile: {
        Row: {
          user_id: string | null;
          first_name: string | null;
          surname: string | null;
          display_name: string | null;
          gender: string | null;
          area_id: string | null;
          area_ids: string[] | null;
          primary_sport: string | null;
          hand: string | null;
          tournament_experience: string | null;
          locale: string | null;
          tz: string | null;
          hidden: boolean | null;
          onboarding_state: Json | null;
          notification_prefs: Json | null;
          role: string | null;
          claimed_player_id: string | null;
          claim_status: string | null;
          created_at: string | null;
        };
        Relationships: [];
      };
      my_quest_progress: {
        Row: {
          quest_key: string | null;
          period_key: string | null;
          progress: number | null;
          done_at: string | null;
          reward_granted_at: string | null;
        };
        Relationships: [];
      };
      my_unlocks: {
        Row: {
          unlock_key: string | null;
          unlocked_at: string | null;
          seen_at: string | null;
        };
        Relationships: [];
      };
      my_votes: {
        Row: {
          id: string | null;
          subject_type: string | null;
          subject_id: string | null;
          option: number | null;
          created_at: string | null;
          resolved_at: string | null;
          outcome: string | null;
          is_upset_call: boolean | null;
          points: number | null;
          day_key: string | null;
        };
        Relationships: [];
      };
      player_sports: {
        Row: {
          player_id: string | null;
          sport_id: string | null;
          hand: string | null;
          level_tier: number | null;
          level_direction: string | null;
          level_status: string | null;
          record: Json | null;
          form: Json | null;
        };
        Relationships: [];
      };
      players: {
        Row: {
          id: string | null;
          first_name: string | null;
          surname: string | null;
          name_forms: Json | null;
          slug: string | null;
          gender: string | null;
          birth_year: number | null;
          is_minor: boolean | null;
          area_id: string | null;
          photo_path: string | null;
          is_claimed: boolean | null;
          status: string | null;
        };
        Relationships: [];
      };
      quest_defs: {
        Row: {
          key: string | null;
          period: string | null;
          target: number | null;
          counter: string | null;
          reward: Json | null;
          title_el: string | null;
          title_en: string | null;
          sort: number | null;
        };
        Relationships: [];
      };
      reaction_counts: {
        Row: {
          match_id: string | null;
          reaction_key: string | null;
          n: number | null;
        };
        Relationships: [];
      };
      sponsored_cards: {
        Row: {
          id: string | null;
          sponsor: string | null;
          title: string | null;
          subtitle: string | null;
          cta_url: string | null;
          placement: string | null;
          area_ids: string[] | null;
        };
        Relationships: [];
      };
      sports: {
        Row: {
          id: string | null;
          name_el: string | null;
          name_en: string | null;
          config: Json | null;
          sort: number | null;
        };
        Relationships: [];
      };
      tournament_events: {
        Row: {
          id: string | null;
          tournament_id: string | null;
          name: string | null;
          format: string | null;
          gender: string | null;
          level_min: number | null;
          level_max: number | null;
        };
        Relationships: [];
      };
      tournaments: {
        Row: {
          id: string | null;
          sport_id: string | null;
          name: string | null;
          area_id: string | null;
          venue: string | null;
          level_min: number | null;
          level_max: number | null;
          entry_deadline: string | null;
          starts_on: string | null;
          ends_on: string | null;
          draw_state: string | null;
          draw_published_at: string | null;
          active: boolean | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      admin_desk: {
        Args: { p_days?: number };
        Returns: Json;
      };
      admin_set_result: {
        Args: { p_match_id: string; p_winner_side: number; p_sets: Json; p_retired?: boolean; p_walkover?: boolean };
        Returns: Json;
      };
      admin_void_match: {
        Args: { p_match_id: string };
        Returns: Json;
      };
      cast_vote: {
        Args: { p_match_id: string; p_side: number; p_client_event_id?: string };
        Returns: Json;
      };
      claim_player: {
        Args: { p_player_id: string };
        Returns: Json;
      };
      find_matching_players: {
        Args: { p_name: string; p_surname: string };
        Returns: { id: string; first_name: string; surname: string; area_id: string; match_score: number }[];
      };
      follow_player: {
        Args: { p_player_id: string; p_relation?: string; p_source?: string };
        Returns: undefined;
      };
      get_feed: {
        Args: { p_limit?: number };
        Returns: Json;
      };
      get_me: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      get_results: {
        Args: { p_days?: number; p_limit?: number };
        Returns: Json;
      };
      mark_inbox_seen: {
        Args: { p_ids: string[] };
        Returns: number;
      };
      resolve_match: {
        Args: { p_match_id: string };
        Returns: Json;
      };
      search_players: {
        Args: { p_query: string; p_limit?: number };
        Returns: { id: string; first_name: string; surname: string; area_id: string; photo_path: string; level_tier: number; level_direction: string; is_claimed: boolean; is_followed: boolean }[];
      };
      unfollow_player: {
        Args: { p_player_id: string };
        Returns: undefined;
      };
      update_profile: {
        Args: { p_patch: Json };
        Returns: Json;
      };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
