-- NetProphet v2 baseline 2/8: reference data, identity, roster, competition.
-- Text + CHECK constraints instead of enums (cheaper to evolve).

-- ---------------------------------------------------------------------------
-- Reference
-- ---------------------------------------------------------------------------
create table core.sports (
  id          text primary key check (id ~ '^[a-z][a-z0-9_]*$'),
  name_el     text not null,
  name_en     text not null,
  -- side size, score model, allowed formats, mixed rules, and the game rule numbers
  config      jsonb not null default '{}'::jsonb,
  active      boolean not null default true,
  sort        int not null default 0,
  created_at  timestamptz not null default now()
);
comment on column core.sports.config is
  'Sport-specific shape: side_size, formats, score model, mixed rules and rules.* (points, freezes, upset thresholds). Nothing sport-specific is hardcoded in functions.';

create table core.areas (
  id        text primary key,
  region    text not null check (region in ('north', 'center', 'south')),
  name_el   text not null,
  name_en   text not null,
  sort      int not null default 0
);

-- ---------------------------------------------------------------------------
-- Roster. A player is sport-agnostic; ratings live in player_sports.
-- ---------------------------------------------------------------------------
create table core.players (
  id                  uuid primary key default gen_random_uuid(),
  first_name          text not null check (btrim(first_name) <> ''),
  surname             text not null check (btrim(surname) <> ''),
  -- grammatical forms (nominative, accusative, genitive, vocative), generated by packages/copy and editable
  name_forms          jsonb not null default '{}'::jsonb,
  -- Greek + Greeklish normalised search columns (ported from v1 first_name_normalized / last_name_normalized)
  first_name_norm     text generated always as (core.normalize_search(first_name)) stored,
  surname_norm        text generated always as (core.normalize_search(surname)) stored,
  search_norm         text generated always as (core.normalize_search(first_name || ' ' || surname)) stored,
  slug                text unique,
  gender              text check (gender in ('m', 'f')),
  birth_year          int check (birth_year between 1900 and 2100),
  is_minor            boolean not null default false,
  area_id             text references core.areas (id),
  photo_path          text,
  claimed_by_user_id  uuid unique references auth.users (id) on delete set null,
  hidden              boolean not null default false,
  source              text not null default 'admin' check (source in ('admin', 'import', 'user')),
  status              text not null default 'active' check (status in ('pending', 'active', 'merged')),
  merged_into         uuid references core.players (id),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  check (status <> 'merged' or merged_into is not null)
);
create index players_surname_norm_idx on core.players (surname_norm);
create index players_search_trgm_idx on core.players using gin (search_norm extensions.gin_trgm_ops);
create trigger players_touch before update on core.players
  for each row execute function core.touch_updated_at();

create table core.player_sports (
  player_id        uuid not null references core.players (id) on delete cascade,
  sport_id         text not null references core.sports (id),
  hand             text check (hand in ('R', 'L')),
  initial_level    numeric(3, 1),                       -- admin, from NTRP
  level_value      numeric(4, 2),                       -- fine value, Pro-only in the client
  level_tier       int,                                 -- shown as «level N»
  level_direction  text not null default 'same' check (level_direction in ('up', 'same', 'down')),
  level_status     text not null default 'pending' check (level_status in ('pending', 'active')),
  record           jsonb not null default '{"singles":{"w":0,"l":0},"doubles":{"w":0,"l":0}}'::jsonb,
  form             jsonb not null default '[]'::jsonb,  -- last 5, newest first: ["W","L",...]
  upset_index      numeric(5, 2),
  updated_at       timestamptz not null default now(),
  primary key (player_id, sport_id)
);

-- ---------------------------------------------------------------------------
-- Profiles (one per auth user) and claims
-- ---------------------------------------------------------------------------
create table core.profiles (
  user_id                 uuid primary key references auth.users (id) on delete cascade,
  first_name              text,
  surname                 text,
  display_name            text,
  gender                  text check (gender in ('m', 'f')),
  area_id                 text references core.areas (id),
  area_ids                text[] not null default '{}',
  primary_sport           text not null default 'tennis' references core.sports (id),
  hand                    text check (hand in ('R', 'L')),
  tournament_experience   text,
  locale                  text not null default 'el' check (locale in ('el', 'en')),
  tz                      text not null default 'Europe/Athens',
  hidden                  boolean not null default false,
  onboarding_state        jsonb not null default '{}'::jsonb,
  notification_prefs      jsonb not null default '{}'::jsonb,
  role                    text not null default 'user' check (role in ('user', 'editor', 'admin')),
  claimed_player_id       uuid unique references core.players (id) on delete set null,
  claim_status            text not null default 'none'
                          check (claim_status in ('none', 'claimed', 'skipped', 'creation_requested')),
  claim_completed_at      timestamptz,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),
  deleted_at              timestamptz
);
create trigger profiles_touch before update on core.profiles
  for each row execute function core.touch_updated_at();

-- circle: who the user knows. Feed ordering uses it (nearest circle first).
create table core.follows (
  user_id     uuid not null references auth.users (id) on delete cascade,
  player_id   uuid not null references core.players (id) on delete cascade,
  relation    text not null default 'known' check (relation in ('known', 'friend')),
  source      text not null default 'profile' check (source in ('onboarding', 'profile', 'card', 'invite')),
  created_at  timestamptz not null default now(),
  primary key (user_id, player_id)
);
create index follows_player_idx on core.follows (player_id);

-- ---------------------------------------------------------------------------
-- Competition
-- ---------------------------------------------------------------------------
create table core.tournaments (
  id                  uuid primary key default gen_random_uuid(),
  sport_id            text not null references core.sports (id),
  name                text not null,
  area_id             text references core.areas (id),
  venue               text,
  level_min           numeric(3, 1),
  level_max           numeric(3, 1),
  entry_deadline      date,
  starts_on           date,
  ends_on             date,
  draw_state          text not null default 'open' check (draw_state in ('open', 'drawn', 'done')),
  draw_published_at   timestamptz,
  is_minor_event      boolean not null default false,
  active              boolean not null default true,       -- suggested in the «+ Ματς» picker
  source              text not null default 'admin' check (source in ('admin', 'import', 'user')),
  external_ref        text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  check (ends_on is null or starts_on is null or ends_on >= starts_on),
  unique (source, external_ref)
);
create trigger tournaments_touch before update on core.tournaments
  for each row execute function core.touch_updated_at();

-- replaces v1 tournament_categories
create table core.tournament_events (
  id             uuid primary key default gen_random_uuid(),
  tournament_id  uuid not null references core.tournaments (id) on delete cascade,
  name           text not null,
  format         text not null check (format in ('singles', 'doubles', 'mixed')),
  gender         text check (gender in ('m', 'f', 'mixed')),
  level_min      numeric(3, 1),
  level_max      numeric(3, 1),
  created_at     timestamptz not null default now()
);
create index tournament_events_tournament_idx on core.tournament_events (tournament_id);

create table core.matches (
  id                      uuid primary key default gen_random_uuid(),
  sport_id                text not null references core.sports (id),
  format                  text not null default 'singles' check (format in ('singles', 'doubles', 'mixed')),
  status                  text not null default 'scheduled'
                          check (status in ('announced', 'scheduled', 'played', 'confirmed', 'disputed', 'void')),
  starts_at               timestamptz,
  locked_at               timestamptz,                      -- admin early lock; voting closes at min(starts_at, locked_at)
  venue                   text,
  area_id                 text references core.areas (id),
  tournament_id           uuid references core.tournaments (id) on delete set null,   -- null = friendly
  event_id                uuid references core.tournament_events (id) on delete set null,
  round                   text,
  source                  text not null default 'admin' check (source in ('admin', 'import', 'user')),
  source_ref              text,
  logged_by               uuid references auth.users (id) on delete set null,
  announced_before_played boolean not null default false,
  counts_for_levels       boolean not null default false,
  approved                boolean not null default true,   -- user-added matches wait for admin approval
  provenance              jsonb not null default '{}'::jsonb,   -- url, run_id, sheet row
  resolved_at             timestamptz,                      -- set by resolve_match
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),
  unique (source, source_ref),
  check (source <> 'user' or logged_by is not null)
);
create index matches_open_idx on core.matches (sport_id, starts_at) where status in ('announced', 'scheduled');
create index matches_tournament_idx on core.matches (tournament_id);
create trigger matches_touch before update on core.matches
  for each row execute function core.touch_updated_at();

-- singles/doubles/mixed through sides: side 1 or 2, position orders a doubles pair
create table core.match_participants (
  match_id   uuid not null references core.matches (id) on delete cascade,
  side       smallint not null check (side in (1, 2)),
  player_id  uuid not null references core.players (id),
  position   smallint not null default 1 check (position in (1, 2)),
  primary key (match_id, player_id),
  unique (match_id, side, position)
);
create index match_participants_player_idx on core.match_participants (player_id);

-- sets are winner-first: [{"w":6,"l":4},{"w":6,"l":7,"tb":[5,7]},{"w":10,"l":8,"stb":true}]
create table core.match_results (
  match_id        uuid primary key references core.matches (id) on delete cascade,
  winner_side     smallint not null check (winner_side in (1, 2)),
  sets            jsonb not null default '[]'::jsonb,
  score_summary   text,                        -- derived by trigger, e.g. '2-1'
  retired         boolean not null default false,
  walkover        boolean not null default false,
  result_version  int not null default 1,
  entered_by      uuid references auth.users (id) on delete set null,
  entered_at      timestamptz not null default now()
);

-- opponent confirmation (member in feed, or non-member via link)
create table core.match_confirmations (
  match_id      uuid not null references core.matches (id) on delete cascade,
  player_id     uuid not null references core.players (id),
  state         text not null default 'pending' check (state in ('pending', 'confirmed', 'disputed', 'not_me')),
  via           text check (via in ('feed', 'link', 'admin')),
  proposed_fix  jsonb,
  at            timestamptz not null default now(),
  primary key (match_id, player_id)
);

create table core.match_links (
  id            uuid primary key default gen_random_uuid(),
  match_id      uuid not null references core.matches (id) on delete cascade,
  token_hash    text not null unique,
  expires_at    timestamptz not null default (now() + interval '7 days'),
  resend_count  int not null default 0,
  opened_at     timestamptz,
  claimed_at    timestamptz,
  created_at    timestamptz not null default now(),
  check (expires_at >= created_at + interval '7 days')
);
