import type { Copy } from './types';

export const en: Copy = {
  common: {
    continue: 'Continue',
    back: 'Back',
  },
  streak: {
    label: 'streak',
  },
  level: {
    label: 'level',
  },
  ladder: {
    title: 'Ladder',
  },
  tabs: {
    vote: 'Vote',
    results: 'Results',
    players: 'Players',
    ladder: 'Ladder',
    me: 'Me',
  },
  header: {
    points: 'points',
  },
  match: {
    today: 'Today',
    tomorrow: 'Tomorrow',
    levelArea: 'level {level} · {area}',
    learnTonight: 'You find out tonight',
    learnTomorrow: 'You find out tomorrow',
    weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    formats: { doubles: 'Doubles', mixed: 'Mixed' },
    friendly: 'Friendly',
    learnAfter: 'You find out after the match',
    rounds: {
      round64: 'Round of 64',
      round32: 'Round of 32',
      round16: 'Second round',
      quarter: 'Quarterfinal',
      semi: 'Semifinal',
      final: 'Final',
    },
  },
  addMatch: {
    cta: '+ Match',
    title: 'Got a match?',
    soon: 'Coming soon.',
  },
  welcome: {
    title: 'Everything about amateur',
    sports: ['tennis.', 'padel.'],
    points: ['Pick the winners', 'See results', 'Know your opponents inside out'],
    tagline: 'Who wins today? Say it first.',
    cta: 'Let’s go',
    later: 'Another time',
  },
  auth: {
    title: 'Get in the game',
    subtitle: 'Type your email and we send you a code.',
    emailLabel: 'Your email',
    emailPlaceholder: 'you@email.com',
    sendCode: 'Send me a code',
    or: 'or',
    google: 'Continue with Google',
    codeTitle: 'Check your email',
    codeSent: 'We sent a 6-digit code to {email}.',
    codeLabel: 'Code',
    verify: 'Let me in',
    resend: 'Send it again',
    changeEmail: 'Different email',
    signOut: 'Sign out',
    errors: {
      invalidEmail: 'That does not look like an email.',
      badCode: 'Wrong or expired code. Try again.',
      tooMany: 'Too many tries. Give it a minute.',
      generic: 'Something went wrong. Try again.',
    },
  },
  feed: {
    title: 'What is on today?',
    subtitle: 'Pick the winners and collect points.',
    end: 'The further down you go, the more matches from players you may not know.',
    empty: 'No matches this day yet.',
    error: 'Could not load. Pull down to try again.',
    voteFailed: 'Your vote did not go through. Try again.',
    votingClosed: 'Voting has closed.',
  },
  result: {
    correct: 'You called it!',
    wrong: 'Not this time',
    beat: 'beat {loser}',
    beatPair: 'beat {losers}',
    points: '+{points} · streak {streak}',
    kept: 'you kept your streak',
    next: 'Next ›',
    done: 'OK',
  },
  results: {
    title: 'Results',
    subtitle: 'What happened on court.',
    yesterday: 'Yesterday',
    dayBefore: 'Two days ago',
    weekdaysOn: ['On Sunday', 'On Monday', 'On Tuesday', 'On Wednesday', 'On Thursday', 'On Friday', 'On Saturday'],
    friendlies: 'Friendlies',
    rounds: {
      round64: 'Round of 64',
      round32: 'Round of 32',
      round16: 'Round of 16',
      quarter: 'Quarter-finals',
      semi: 'Semi-finals',
      final: 'Final',
    },
    upset: 'Upset',
    calledIt: 'Called it · +{points}',
    line: '{pct}% said {name}',
    retired: 'ret.',
    walkover: 'w/o',
    empty: 'No results yet. When a match ends, you will see it here.',
    error: 'Did not load. Pull down to try again.',
  },
  placeholder: {
    results: 'Results will show up here.',
    players: 'Players will show up here.',
    ladder: 'The Ladder opens soon.',
    me: 'Your profile will show up here.',
  },
};
