#!/usr/bin/env node
// Generates src/types.ts from a live database: the `api` schema only (views + RPCs), in the shape of
// `supabase gen types typescript`, so it works with createClient<Database, 'api'>.
// The Supabase CLI runs pg-meta in a container; this script only needs `psql`, so it also runs in CI
// right next to the pgTAP run (scripts/v2-db-test.sh does that and fails the build when types are stale).
//
// Usage: PGHOST=... PGPORT=... PGUSER=... PGDATABASE=... node scripts/gen-types.mjs [--out src/types.ts]
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const outIdx = process.argv.indexOf('--out');
const out = outIdx > -1 ? process.argv[outIdx + 1] : null;

function psqlJson(sql) {
  const raw = execFileSync('psql', ['-X', '-q', '-t', '-A', '-v', 'ON_ERROR_STOP=1', '-c', sql], {
    encoding: 'utf8',
    env: process.env,
  });
  return JSON.parse(raw.trim() || 'null');
}

const SCALAR = {
  uuid: 'string', text: 'string', varchar: 'string', bpchar: 'string', citext: 'string', name: 'string',
  date: 'string', time: 'string', timetz: 'string', timestamp: 'string', timestamptz: 'string', interval: 'string',
  int2: 'number', int4: 'number', int8: 'number', float4: 'number', float8: 'number', numeric: 'number', oid: 'number',
  bool: 'boolean', json: 'Json', jsonb: 'Json', void: 'undefined',
};
function ts(typname, elem) {
  if (elem) return `${SCALAR[elem] ?? 'unknown'}[]`;
  return SCALAR[typname] ?? 'unknown';
}

const views = psqlJson(`
  select coalesce(jsonb_agg(v order by v->>'name'), '[]') from (
    select jsonb_build_object('name', c.relname, 'cols', (
      select jsonb_agg(jsonb_build_object('name', a.attname, 'typ', t.typname,
                                          'elem', case when t.typcategory = 'A' then et.typname end) order by a.attnum)
        from pg_attribute a
        join pg_type t on t.oid = a.atttypid
        left join pg_type et on et.oid = t.typelem and t.typcategory = 'A'
       where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped)) as v
      from pg_class c where c.relnamespace = 'api'::regnamespace and c.relkind in ('v', 'm')
  ) s`);

const fns = psqlJson(`
  select coalesce(jsonb_agg(f order by f->>'name'), '[]') from (
    select jsonb_build_object(
      'name', p.proname,
      'set', p.proretset,
      'ret', rt.typname,
      'retelem', case when rt.typcategory = 'A' then ret.typname end,
      'ndefaults', p.pronargdefaults,
      'args', (
        select coalesce(jsonb_agg(jsonb_build_object('name', coalesce(p.proargnames[i], 'arg' || i),
                                                      'typ', t.typname,
                                                      'elem', case when t.typcategory = 'A' then et.typname end) order by i), '[]')
          from (select coalesce(p.proallargtypes, string_to_array(p.proargtypes::text, ' ')::oid[]) as types) a
          cross join generate_subscripts(a.types, 1) i
          join pg_type t on t.oid = a.types[i]
          left join pg_type et on et.oid = t.typelem and t.typcategory = 'A'
         where coalesce(p.proargmodes[i], 'i') in ('i', 'b')),
      'cols', (
        select jsonb_agg(jsonb_build_object('name', p.proargnames[i], 'typ', t.typname,
                                            'elem', case when t.typcategory = 'A' then et.typname end) order by i)
          from generate_subscripts(p.proargmodes, 1) i
          join pg_type t on t.oid = p.proallargtypes[i]
          left join pg_type et on et.oid = t.typelem and t.typcategory = 'A'
         where p.proargmodes[i] = 't')
    ) as f
    from pg_proc p
    join pg_type rt on rt.oid = p.prorettype
    left join pg_type ret on ret.oid = rt.typelem and rt.typcategory = 'A'
    where p.pronamespace = 'api'::regnamespace and p.prokind = 'f'
  ) s`);

const pad = (n) => '  '.repeat(n);
let o = '';
o += `// GENERATED by packages/db/scripts/gen-types.mjs from the v2 database (api schema). Do not edit by hand.\n`;
o += `// Regenerate: scripts/v2-db-test.sh with V2_DB_WRITE_TYPES=1 (or pnpm --filter @netprophet/db gen-types against a migrated DB).\n\n`;
o += `export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\n\n`;
o += `export type Database = {\n${pad(1)}api: {\n`;
o += `${pad(2)}Tables: { [_ in never]: never };\n`;
o += `${pad(2)}Views: {\n`;
for (const v of views) {
  o += `${pad(3)}${v.name}: {\n${pad(4)}Row: {\n`;
  for (const c of v.cols) o += `${pad(5)}${c.name}: ${ts(c.typ, c.elem)} | null;\n`;
  o += `${pad(4)}};\n${pad(4)}Relationships: [];\n${pad(3)}};\n`;
}
o += `${pad(2)}};\n${pad(2)}Functions: {\n`;
for (const f of fns) {
  const firstOpt = f.args.length - f.ndefaults;
  const args = f.args.map((a, i) => `${a.name}${i >= firstOpt ? '?' : ''}: ${ts(a.typ, a.elem)}`).join('; ');
  let ret;
  if (f.cols) ret = `{ ${f.cols.map((c) => `${c.name}: ${ts(c.typ, c.elem)}`).join('; ')} }[]`;
  else ret = f.set ? `${ts(f.ret, f.retelem)}[]` : ts(f.ret, f.retelem);
  o += `${pad(3)}${f.name}: {\n${pad(4)}Args: ${f.args.length ? `{ ${args} }` : 'Record<PropertyKey, never>'};\n${pad(4)}Returns: ${ret};\n${pad(3)}};\n`;
}
o += `${pad(2)}};\n${pad(2)}Enums: { [_ in never]: never };\n${pad(2)}CompositeTypes: { [_ in never]: never };\n${pad(1)}};\n};\n`;

if (out) writeFileSync(out, o);
else process.stdout.write(o);
