-- Add balance and other missing columns to profiles table
ALTER TABLE profiles ADD COLUMN
IF NOT EXISTS balance INTEGER DEFAULT 1000;
ALTER TABLE profiles ADD COLUMN
IF NOT EXISTS has_received_welcome_bonus BOOLEAN DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN
IF NOT EXISTS total_winnings INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN
IF NOT EXISTS total_losses INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN
IF NOT EXISTS won_bets INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN
IF NOT EXISTS lost_bets INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN
IF NOT EXISTS total_bets INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN
IF NOT EXISTS referral_bonus_earned INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN
IF NOT EXISTS leaderboard_prizes_earned INTEGER DEFAULT 0; 